Объединиение в один CSV

In [4]:
# import pandas as pd
# import glob
# import os
#
# path = r"D:\Photo"
# all_files = glob.glob(os.path.join(path, "*.csv"))
# main_df = None
# for file in all_files:
#     df = pd.read_table(file, sep=";")
#     if main_df is None:
#         main_df = df
#     else:
#         main_df = pd.concat([main_df, df], ignore_index=True)
# main_df.to_csv("true_output.csv", index=False, encoding='utf-8-sig')
# print(main_df)

      accommodation_type             author        author_type deal_type  \
0                   flat       Центр Инвест  real_estate_agent      sale
1                   flat  Apple Real Estate  real_estate_agent      sale
2                   flat       ID 119690304          homeowner      sale
3                   flat       Центр Инвест  real_estate_agent      sale
4                   flat          Whitewill  real_estate_agent      sale
...                  ...                ...                ...       ...
84349                NaN                NaN                NaN       NaN
84350                NaN                NaN                NaN       NaN
84351                NaN                NaN                NaN       NaN
84352                NaN                NaN                NaN       NaN
84353                NaN                NaN                NaN       NaN

                                             description        district  \
0      О ПРОЕКТЕ:\n\nWill Towers — жилой комплекс биз...         Раменки
1      Лот 1000259. Виктория Шевцова.\n\nРады предлож...         Раменки
2      УСЛУГИ ПРОСЬБА НЕ ПРЕДЛАГАТЬ !!! \nПродает соб...  Филевский парк
3      О ПРОЕКТЕ:\n\nWill Towers — жилой комплекс биз...         Раменки
4      Квартира с двумя спальнями в комплексе премиум...         Раменки
...                                                  ...             ...
84349                                                NaN             NaN
84350                                                NaN             NaN
84351                                                NaN             NaN
84352                                                NaN             NaN
84353                                                NaN             NaN

       finish_type  floor  floors_count  heating_type  ...       price  \
0      Без отделки   35.0          56.0          -1.0  ...  28127104.0
1               -1    9.0          19.0          -1.0  ...  41500000.0
2               -1    7.0           8.0          -1.0  ...  17850000.0
3      Без отделки   33.0          56.0          -1.0  ...  38320818.0
4         Чистовая   23.0          40.0          -1.0  ...  51000000.0
...            ...    ...           ...           ...  ...         ...
84349          NaN    NaN           NaN           NaN  ...         NaN
84350          NaN    NaN           NaN           NaN  ...         NaN
84351          NaN    NaN           NaN           NaN  ...         NaN
84352          NaN    NaN           NaN           NaN  ...         NaN
84353          NaN    NaN           NaN           NaN  ...         NaN

      residential_complex rooms_count                      street  \
0             Will Towers         2.0  проспект Генерала Дорохова
1         Золотые Ключи 2         2.0                    Минская
2                     NaN         2.0            Василисы Кожиной
3             Will Towers         2.0  проспект Генерала Дорохова
4                 Нова ЖК         2.0                         NaN
...                   ...         ...                         ...
84349                 NaN         NaN                         NaN
84350                 NaN         NaN                         NaN
84351                 NaN         NaN                         NaN
84352                 NaN         NaN                         NaN
84353                 NaN         NaN                         NaN

      total_meters  transport_score underground  \
0             51.3              5.2     Минская
1             67.0             -1.0     Минская
2             40.0             -1.0     Минская
3             73.4              5.2     Минская
4             54.0             -1.0     Минская
...            ...              ...         ...
84349          NaN              NaN         NaN
84350          NaN              NaN         NaN
84351          NaN              NaN         NaN
84352          NaN              NaN         NaN
84353          NaN              NaN         NaN

                                                     url  \
0      https://www.cian.ru/sale/flat/320392576/?mlSea...
1      https://www.cian.ru/sale/flat/326688167/?mlSea...
2      https://www.cian.ru/sale/flat/322956324/?mlSea...
3      https://www.cian.ru/sale/flat/320392568/?mlSea...
4      https://www.cian.ru/sale/flat/327116733/?mlSea...
...                                                  ...
84349                                                NaN
84350                                                NaN
84351                                                NaN
84352                                                NaN
84353                                                NaN

       year_of_construction  \
0                      2024
1                      2004
2                      1960
3                      2024
4                      2027
...                     ...
84349                   NaN
84350                   NaN
84351                   NaN
84352                   NaN
84353                   NaN

       Price,Apartment type,Metro station,Minutes to metro,Region,Number of rooms,Area,Living area,Kitchen area,Floor,Number of floors,Renovation
0                                                    NaN
1                                                    NaN
2                                                    NaN
3                                                    NaN
4                                                    NaN
...                                                  ...
84349  4768792.0,New building,Котельники,8.0,Moscow r...
84350  5900000.0,New building,Домодедовская,25.0,Mosc...
84351  3700000.0,New building,Котельники,30.0,Moscow ...
84352  5768869.0,New building,Жулебино,14.0,Moscow re...
84353  6839157.0,New building,Котельники,8.0,Moscow r...

[84354 rows x 29 columns]

In [1]:
import pandas as pd
import glob
import os

df = pd.read_table(r"C:\Users\User\Desktop\Учеба\Практики\Семак 2\ОМО\Курсач\true_output.csv", sep=",")
df = df.drop_duplicates()

C:\Users\User\AppData\Local\Temp\ipykernel_21452\2861496318.py:5: DtypeWarning: Columns (0: accommodation_type, 1: author, 2: author_type, 3: deal_type, 4: description, 5: district, 6: finish_type, 7: house_material_type, 8: house_number, 9: kitchen_meters, 10: living_meters, 11: location, 12: nearest_metro, 13: residential_complex, 14: street, 15: underground, 16: url, 17: year_of_construction, 18: Price,Apartment type,Metro station,Minutes to metro,Region,Number of rooms,Area,Living area,Kitchen area,Floor,Number of floors,Renovation) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_table(r"C:\Users\User\Desktop\Учеба\Практики\Семак 2\ОМО\Курсач\true_output.csv", sep=",")

Посмотрим характеристики

In [3]:
df.info()
df.head()

<class 'pandas.DataFrame'>
Index: 128413 entries, 0 to 128777
Data columns (total 16 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   accommodation_type   128413 non-null  str
 1   author               127865 non-null  str
 2   author_type          127865 non-null  str
 3   deal_type            128413 non-null  str
 4   district             124060 non-null  str
 5   floor                128413 non-null  int64
 6   floors_count         128413 non-null  int64
 7   house_number         120334 non-null  str
 8   location             128413 non-null  str
 9   price                128413 non-null  int64
 10  residential_complex  58025 non-null   str
 11  rooms_count          128413 non-null  int64
 12  street               121909 non-null  str
 13  total_meters         128413 non-null  float64
 14  underground          128409 non-null  str
 15  url                  128413 non-null  str
dtypes: float64(1), int64(4), str(11)
memory usage: 16.7 MB

,accommodation_type,author,author_type,deal_type,district,floor,floors_count,house_number,location,price,residential_complex,rooms_count,street,total_meters,underground,url
0,flat,MR,developer,sale,Мещанский,9,13,14,Москва,158708090,Клубный дом Forum,1,Садовая-Сухаревская,73.51,Сухаревская,https://www.cian.ru/sale/flat/321435298/?mlSea...
1,flat,Этажи Москва,real_estate_agent,sale,Ново-Переделкино,19,23,2к2,Москва,22900000,FoRest,1,Чоботовская,43.50,Новопеределкино,https://www.cian.ru/sale/flat/326444525/?mlSea...
2,flat,ИНФИНИТИ,real_estate_agent,sale,Бирюлево Восточное,14,17,46к1,Москва,10900000,NaN,1,Липецкая,38.40,Лебедянская,https://www.cian.ru/sale/flat/322694215/?mlSea...
3,flat,Sminex,developer,sale,Басманный,2,6,5С4,Москва,194740000,Исторический дом,1,Потаповский переулок,79.00,Чистые пруды,https://www.cian.ru/sale/flat/326080890/?mlSea...
4,flat,Юрий Артамонов,realtor,sale,Теплый Стан,13,16,30К1,Москва,18500000,NaN,1,Островитянова,34.90,Коньково,https://www.cian.ru/sale/flat/326908765/?mlSea...

Удалим ненужные столбцы: author, author_type, house_number, residental_complex, street,url

In [4]:
df.drop(columns=['author', 'author_type', 'house_number', 'residential_complex', 'street','url'], inplace=True)
df.head()

,accommodation_type,deal_type,district,floor,floors_count,location,price,rooms_count,total_meters,underground
0,flat,sale,Мещанский,9,13,Москва,158708090,1,73.51,Сухаревская
1,flat,sale,Ново-Переделкино,19,23,Москва,22900000,1,43.50,Новопеределкино
2,flat,sale,Бирюлево Восточное,14,17,Москва,10900000,1,38.40,Лебедянская
3,flat,sale,Басманный,2,6,Москва,194740000,1,79.00,Чистые пруды
4,flat,sale,Теплый Стан,13,16,Москва,18500000,1,34.90,Коньково

In [5]:
print(df['accommodation_type'].value_counts())
df['deal_type'].value_counts()
df['location'].value_counts()

accommodation_type
flat    128413
Name: count, dtype: int64

location
Москва    128413
Name: count, dtype: int64

Удалим столбцы accommodation-type, location и deal_type т.к в них лишь одно уникальное значение. Также удалим столбец underground

In [6]:
df.drop(columns=["accommodation_type", "deal_type", "underground", "location"], inplace=True)

Посмотрим, в скольких строках данных содержаться пропуски и сравним с общим размером записей

In [7]:
print(df.shape)
df.isna().sum(axis=0)

(128413, 6)

district        4353
floor              0
floors_count       0
price              0
rooms_count        0
total_meters       0
dtype: int64

Удалим строки с пропусками данных в колонке district

In [8]:
df.dropna()

,district,floor,floors_count,price,rooms_count,total_meters
0,Мещанский,9,13,158708090,1,73.51
1,Ново-Переделкино,19,23,22900000,1,43.50
2,Бирюлево Восточное,14,17,10900000,1,38.40
3,Басманный,2,6,194740000,1,79.00
4,Теплый Стан,13,16,18500000,1,34.90
...,...,...,...,...,...,...
128773,Нагатинский затон,18,24,97981690,5,159.90
128774,Нагатинский затон,18,24,99268503,5,162.00
128775,Можайский,13,13,168600000,5,196.60
128776,Арбат,2,5,199000000,5,130.00
128777,Пресненский,19,21,206500000,5,227.00

Вместо районов будем использовать округа

In [9]:
import json
with open("county_district.json", 'r', encoding='utf-8') as file:
    districts = json.load(file)
new_districts = dict()
for i in districts:
    name = i['name']
    county_id = i['county_id']
    new_districts[name] = county_id
with open("county.json", 'r', encoding='utf-8') as file:
    countis = json.load(file)
new_countis = dict()
for i in countis:
    short_name = i['short']
    id_c = i['id']
    new_countis[id_c] = short_name
print(new_countis)
print(new_districts)

df['district'] = df['district'].replace(new_districts)
df.head()

{1: 'СЗАО', 2: 'САО', 3: 'СВАО', 4: 'ЗАО', 5: 'ЦАО', 6: 'ВАО', 7: 'ЮЗАО', 8: 'ЮАО', 9: 'ЮВАО', 10: 'ЗелАО', 11: 'НАО', 12: 'ТАО'}
{'Куркино': 1, 'Митино': 1, 'Покровское-Стрешнево': 1, 'Северное Тушино': 1, 'Строгино': 1, 'Хорошево-Мневники': 1, 'Щукино': 1, 'Южное Тушино': 1, 'Северный (САО)': 2, 'Аэропорт': 2, 'Беговой': 2, 'Бескудниковский': 2, 'Войковский': 2, 'Восточное Дегунино': 2, 'Западное Дегунино': 2, 'Головинский': 2, 'Дмитровский': 2, 'Коптево': 2, 'Левобережный': 2, 'Молжаниновский': 2, 'Савеловский': 2, 'Сокол': 2, 'Тимирязевский': 2, 'Ховрино': 2, 'Хорошевский': 2, 'Алексеевский': 3, 'Алтуфьевский': 3, 'Бабушкинский': 3, 'Бибирево': 3, 'Бутырский': 3, 'Лианозово': 3, 'Лосиноостровский': 3, 'Марфино': 3, 'Марьина Роща': 3, 'Останкинский': 3, 'Отрадное': 3, 'Ростокино': 3, 'Свиблово': 3, 'Северное Медведково': 3, 'Южное Медведково': 3, 'Северный': 3, 'Ярославский': 3, 'Внуково': 4, 'Дорогомилово': 4, 'Крылатское': 4, 'Кунцево': 4, 'Можайский': 4, 'Ново-Переделкино': 4, 'Очаково-Матвеевское': 4, 'Проспект Вернадского': 4, 'Раменки': 4, 'Солнцево': 4, 'Тропарево-Никулино': 4, 'Филевский Парк': 4, 'Фили-Давыдково': 4, 'Арбат': 5, 'Басманный': 5, 'Замоскворечье': 5, 'Красносельский': 5, 'Мещанский': 5, 'Пресненский': 5, 'Таганский': 5, 'Тверской': 5, 'Хамовники': 5, 'Якиманка': 5, 'Богородское': 6, 'Вешняки': 6, 'Восточное Измайлово': 6, 'Северное Измайлово': 6, 'Восточный': 6, 'Гольяново': 6, 'Ивановское': 6, 'Измайлово': 6, 'Косино-Ухтомский': 6, 'Метрогородок': 6, 'Новогиреево': 6, 'Новокосино': 6, 'Перово': 6, 'Преображенское': 6, 'Соколиная Гора': 6, 'Сокольники': 6, 'Академический': 7, 'Гагаринский': 7, 'Зюзино': 7, 'Коньково': 7, 'Котловка': 7, 'Ломоносовский': 7, 'Обручевский': 7, 'Северное Бутово': 7, 'Южное Бутово': 7, 'Теплый Стан': 7, 'Черемушки': 7, 'Ясенево': 7, 'Бирюлево Восточное': 8, 'Бирюлево Западное': 8, 'Братеево': 8, 'Даниловский': 8, 'Донской': 8, 'Зябликово': 8, 'Москворечье-Сабурово': 8, 'Нагатино-Садовники': 8, 'Нагатинский Затон': 8, 'Нагорный': 8, 'Орехово-Борисово Северное': 8, 'Орехово-Борисово Южное': 8, 'Царицыно': 8, 'Чертаново Северное': 8, 'Чертаново Центральное': 8, 'Чертаново Южное': 8, 'Выхино-Жулебино': 9, 'Капотня': 9, 'Кузьминки': 9, 'Лефортово': 9, 'Люблино': 9, 'Марьино': 9, 'Некрасовка': 9, 'Нижегородский': 9, 'Печатники': 9, 'Рязанский': 9, 'Текстильщики': 9, 'Южнопортовый': 9, 'Крюково': 10, 'Матушкино': 10, 'Савёлки': 10, 'Силино': 10, 'Старое Крюково': 10, 'Внуковское': 11, 'Воскресенское': 11, 'Десёновское': 11, 'Кокошкино': 11, 'Марушкинское': 11, 'Московский': 11, 'Мосрентген': 11, 'Рязановское': 11, 'Сосенское': 11, 'Филимонковское': 11, 'Щербинка': 11, 'Вороновское': 12, 'Киевский': 12, 'Кленовское': 12, 'Краснопахорское': 12, 'Михайлово-Ярцевское': 12, 'Новофедоровское': 12, 'Первомайское': 12, 'Роговское': 12, 'Троицк': 12, 'Щаповское': 12}

  district  floor  floors_count      price  rooms_count  total_meters
0        5      9            13  158708090            1         73.51
1        4     19            23   22900000            1         43.50
2        8     14            17   10900000            1         38.40
3        5      2             6  194740000            1         79.00
4        7     13            16   18500000            1         34.90

Проверим корректность замены

In [10]:
df['district'].value_counts()

district
5                                                                          30146
4                                                                          16910
2                                                                          14530
9                                                                          12867
8                                                                          10588
1                                                                          10230
7                                                                          10177
3                                                                           7385
6                                                                           6343
Марьина роща                                                                1334
Нагатинский затон                                                           1071
Филевский парк                                                               926
Соколиная гора                                                               881
10                                                                           661
так как проект расположен всего в 1 км от главной автомагистрали города        4
Лучшая 3кв-ра в Алексеевском е3-комн. квартира                                 4
инновационного образовательного центра                                         3
Name: count, dtype: int64

Исправим недостатки

In [11]:
countis = {
    "Марьина роща": 3,
    "Филевсий парк": 4,
    "Соколиная гора": 6,
    "Нагатинский затон":8,
    "Филевский парк": 4

}
df['district'] = df['district'].replace(countis)
df['district'].value_counts()

district
5                                                                          30146
4                                                                          17836
2                                                                          14530
9                                                                          12867
8                                                                          11659
1                                                                          10230
7                                                                          10177
3                                                                           8719
6                                                                           7224
10                                                                           661
так как проект расположен всего в 1 км от главной автомагистрали города        4
Лучшая 3кв-ра в Алексеевском е3-комн. квартира                                 4
инновационного образовательного центра                                         3
Name: count, dtype: int64

Удалим мусор

In [12]:
df['district'] = pd.to_numeric(df['district'], errors='coerce')
df = df.dropna(subset=['district'])
df['district'].value_counts()

district
5.0     30146
4.0     17836
2.0     14530
9.0     12867
8.0     11659
1.0     10230
7.0     10177
3.0      8719
6.0      7224
10.0      661
Name: count, dtype: int64

Применим OneHotEncoder для столбца district

In [13]:
df = pd.get_dummies(df, columns=['district'])
df.head()

,floor,floors_count,price,rooms_count,total_meters,district_1.0,district_2.0,district_3.0,district_4.0,district_5.0,district_6.0,district_7.0,district_8.0,district_9.0,district_10.0
0,9,13,158708090,1,73.51,False,False,False,False,True,False,False,False,False,False
1,19,23,22900000,1,43.50,False,False,False,True,False,False,False,False,False,False
2,14,17,10900000,1,38.40,False,False,False,False,False,False,False,True,False,False
3,2,6,194740000,1,79.00,False,False,False,False,True,False,False,False,False,False
4,13,16,18500000,1,34.90,False,False,False,False,False,False,True,False,False,False

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

y = df['price']
df.drop(columns=['price'], inplace=True)
X = df
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)



regressor = LinearRegression()
regressor.fit(X_train, y_train)




mine = [10, 18, 3, 60, False, False, False, False, False, False, True, False, False, False]


# or
mine = [mine]

a = regressor.predict(mine)
print(a)

y_pred = regressor.predict(X_test)


score_r2 = r2_score(y_test, y_pred)
mse_score = mean_squared_error(y_test, y_pred)

print(f"score_r2 = {score_r2}")
print(f"mse score = {mse_score}")
from sklearn.metrics import mean_absolute_percentage_error
mape = mean_absolute_percentage_error(y_test, y_pred) * 100
print(f"MAPE: {mape:.1f}%")

[-41551350.37451831]
score_r2 = 0.6034562207828751
mse score = 1.5051556882998218e+16
MAPE: 95.8%

C:\Users\User\Desktop\Учеба\Project\LinearRegression\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

knn

In [15]:
from sklearn.neighbors import KNeighborsRegressor

regressor = KNeighborsRegressor()
regressor.fit(X_train, y_train)


mine = [10, 18, 3, 60, False, False, False, False, False, False, True, False, False, False]


# or
mine = [mine]

a = regressor.predict(mine)
print(a)


y_pred = regressor.predict(X_test)


score_r2 = r2_score(y_test, y_pred)
mse_score = mean_squared_error(y_test, y_pred)

print(f"score_r2 = {score_r2}")
print(f"mse score = {mse_score}")
from sklearn.metrics import mean_absolute_percentage_error
mape = mean_absolute_percentage_error(y_test, y_pred) * 100
print(f"MAPE: {mape:.1f}%")

C:\Users\User\Desktop\Учеба\Project\LinearRegression\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(

[27900000.]
score_r2 = 0.9427211521530968
mse score = 2174125233441645.5
MAPE: 2.8%

tree

In [20]:
from sklearn.tree import DecisionTreeRegressor

from sklearn.metrics import mean_absolute_percentage_error




regressor = DecisionTreeRegressor(max_depth=5)
regressor.fit(X_train, y_train)


mine = [10, 18, 3, 60, False, False, False, False, False, False, True, False, False, False]


# or
mine = [mine]

a = regressor.predict(mine)
print(a)




y_pred = regressor.predict(X_test)


score_r2 = r2_score(y_test, y_pred)
mse_score = mean_squared_error(y_test, y_pred)

print(f"score_r2 = {score_r2}")
print(f"mse score = {mse_score}")
mape = mean_absolute_percentage_error(y_test, y_pred) * 100
print(f"MAPE: {mape:.1f}%")

[19042025.8637733]
score_r2 = 0.745016162519027
mse score = 9678385931729920.0
MAPE: 39.9%

C:\Users\User\Desktop\Учеба\Project\LinearRegression\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(