Объединиение в один CSV

In [25]:
# import pandas as pd
# import glob
# import os
#
# path = r"D:\Photo"
# all_files = glob.glob(os.path.join(path, "*.csv"))
# main_df = None
# for file in all_files:
#     df = pd.read_table(file, sep=";")
#     if main_df is None:
#         main_df = df
#     else:
#         main_df = pd.concat([main_df, df], ignore_index=True)
# main_df.to_csv("true_output.csv", index=False, encoding='utf-8-sig')
# print(main_df)

In [26]:
import pandas as pd
import glob
import os

df = pd.read_table(r"final.csv", sep=";")
df = df.drop_duplicates()

Посмотрим характеристики

In [27]:
df.info()
df.head()

<class 'pandas.DataFrame'>
Index: 55152 entries, 0 to 61677
Data columns (total 28 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   accommodation_type    55152 non-null  str
 1   author                54079 non-null  str
 2   author_type           54079 non-null  str
 3   deal_type             55152 non-null  str
 4   description           55152 non-null  str
 5   district              41736 non-null  str
 6   finish_type           55152 non-null  str
 7   floor                 55152 non-null  int64
 8   floors_count          55152 non-null  int64
 9   heating_type          55152 non-null  int64
 10  house_material_type   55152 non-null  str
 11  house_number          48252 non-null  str
 12  kitchen_meters        55152 non-null  str
 13  living_meters         55152 non-null  str
 14  location              55152 non-null  str
 15  metro_distance        55152 non-null  int64
 16  nearest_metro         55118 non-null  str
 17  object_type           55152 non-null  int64
 18  phone                 55151 non-null  float64
 19  price                 55152 non-null  int64
 20  residential_complex   30791 non-null  str
 21  rooms_count           55152 non-null  int64
 22  street                47459 non-null  str
 23  total_meters          55152 non-null  float64
 24  transport_score       55152 non-null  float64
 25  underground           50581 non-null  str
 26  url                   55152 non-null  str
 27  year_of_construction  55152 non-null  str
dtypes: float64(3), int64(7), str(18)
memory usage: 12.2 MB

,accommodation_type,author,author_type,deal_type,description,district,finish_type,floor,floors_count,heating_type,...,phone,price,residential_complex,rooms_count,street,total_meters,transport_score,underground,url,year_of_construction
0,flat,Центр Инвест,real_estate_agent,sale,О ПРОЕКТЕ:\n\nWill Towers — жилой комплекс биз...,Раменки,Без отделки,35,56,-1,...,7.923071e+10,28127104,Will Towers,2,проспект Генерала Дорохова,51.3,5.2,Минская,https://www.cian.ru/sale/flat/320392576/?mlSea...,2024
1,flat,Apple Real Estate,real_estate_agent,sale,Лот 1000259. Виктория Шевцова.\n\nРады предлож...,Раменки,-1,9,19,-1,...,7.915314e+10,41500000,Золотые Ключи 2,2,Минская,67.0,-1.0,Минская,https://www.cian.ru/sale/flat/326688167/?mlSea...,2004
2,flat,ID 119690304,homeowner,sale,УСЛУГИ ПРОСЬБА НЕ ПРЕДЛАГАТЬ !!! \nПродает соб...,Филевский парк,-1,7,8,-1,...,7.916816e+10,17850000,NaN,2,Василисы Кожиной,40.0,-1.0,Минская,https://www.cian.ru/sale/flat/322956324/?mlSea...,1960
3,flat,Центр Инвест,real_estate_agent,sale,О ПРОЕКТЕ:\n\nWill Towers — жилой комплекс биз...,Раменки,Без отделки,33,56,-1,...,7.923071e+10,38320818,Will Towers,2,проспект Генерала Дорохова,73.4,5.2,Минская,https://www.cian.ru/sale/flat/320392568/?mlSea...,2024
4,flat,Whitewill,real_estate_agent,sale,Квартира с двумя спальнями в комплексе премиум...,Раменки,Чистовая,23,40,-1,...,7.985722e+10,51000000,Нова ЖК,2,NaN,54.0,-1.0,Минская,https://www.cian.ru/sale/flat/327116733/?mlSea...,2027

Удалим ненужные столбцы: author, author_type, house_number, residental_complex, street,url

In [28]:
df.drop(columns=['author', 'author_type', 'house_number', 'residential_complex', 'street','url'], inplace=True)
df.head()

,accommodation_type,deal_type,description,district,finish_type,floor,floors_count,heating_type,house_material_type,kitchen_meters,...,metro_distance,nearest_metro,object_type,phone,price,rooms_count,total_meters,transport_score,underground,year_of_construction
0,flat,sale,О ПРОЕКТЕ:\n\nWill Towers — жилой комплекс биз...,Раменки,Без отделки,35,56,-1,Монолитный,6 м²,...,19,Минская,-1,7.923071e+10,28127104,2,51.3,5.2,Минская,2024
1,flat,sale,Лот 1000259. Виктория Шевцова.\n\nРады предлож...,Раменки,-1,9,19,-1,-1,18 м²,...,16,Ломоносовский проспект,-1,7.915314e+10,41500000,2,67.0,-1.0,Минская,2004
2,flat,sale,УСЛУГИ ПРОСЬБА НЕ ПРЕДЛАГАТЬ !!! \nПродает соб...,Филевский парк,-1,7,8,-1,-1,15 м²,...,11,Филёвский парк,-1,7.916816e+10,17850000,2,40.0,-1.0,Минская,1960
3,flat,sale,О ПРОЕКТЕ:\n\nWill Towers — жилой комплекс биз...,Раменки,Без отделки,33,56,-1,Монолитный,"6,1 м²",...,19,Минская,-1,7.923071e+10,38320818,2,73.4,5.2,Минская,2024
4,flat,sale,Квартира с двумя спальнями в комплексе премиум...,Раменки,Чистовая,23,40,-1,-1,-1,...,15,Минская,-1,7.985722e+10,51000000,2,54.0,-1.0,Минская,2027

In [29]:
print(df['accommodation_type'].value_counts())
df['deal_type'].value_counts()
df['location'].value_counts()

accommodation_type
flat    55152
Name: count, dtype: int64

location
Москва    55152
Name: count, dtype: int64

Удалим столбцы accommodation-type, location и deal_type т.к в них лишь одно уникальное значение. Также удалим столбец underground

In [30]:
df.drop(columns=["accommodation_type", "deal_type", "underground", "location", "description", "nearest_metro"], inplace=True)

Посмотрим, в скольких строках данных содержаться пропуски и сравним с общим размером записей

In [31]:
print(df.shape)
df.isna().sum(axis=0)

(55152, 16)

district                13416
finish_type                 0
floor                       0
floors_count                0
heating_type                0
house_material_type         0
kitchen_meters              0
living_meters               0
metro_distance              0
object_type                 0
phone                       1
price                       0
rooms_count                 0
total_meters                0
transport_score             0
year_of_construction        0
dtype: int64

Удалим строки с пропусками данных в колонке district

In [32]:
df.dropna()

,district,finish_type,floor,floors_count,heating_type,house_material_type,kitchen_meters,living_meters,metro_distance,object_type,phone,price,rooms_count,total_meters,transport_score,year_of_construction
0,Раменки,Без отделки,35,56,-1,Монолитный,6 м²,"33,3 м²",19,-1,7.923071e+10,28127104,2,51.3,5.2,2024
1,Раменки,-1,9,19,-1,-1,18 м²,20 м²,16,-1,7.915314e+10,41500000,2,67.0,-1.0,2004
2,Филевский парк,-1,7,8,-1,-1,15 м²,20 м²,11,-1,7.916816e+10,17850000,2,40.0,-1.0,1960
3,Раменки,Без отделки,33,56,-1,Монолитный,"6,1 м²","44,8 м²",19,-1,7.923071e+10,38320818,2,73.4,5.2,2024
4,Раменки,Чистовая,23,40,-1,-1,-1,49 м²,15,-1,7.985722e+10,51000000,2,54.0,-1.0,2027
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61671,Бескудниковский,-1,2,16,-1,-1,8 м²,46 м²,11,-1,7.916591e+10,16900000,3,65.0,-1.0,1976
61672,Косино-Ухтомский,-1,3,12,-1,-1,"30,8 м²","31,1 м²",5,-1,7.923072e+10,17000000,3,76.8,-1.0,2022
61674,Выхино-Жулебино,-1,3,9,-1,-1,6 м²,"44,3 м²",18,-1,7.986264e+10,17000000,3,58.8,-1.0,1968
61675,Кунцево,-1,1,12,-1,-1,7 м²,"46,4 м²",11,-1,7.910474e+10,16900000,3,63.7,-1.0,1974
61677,Кузьминки,-1,3,17,-1,-1,10 м²,45 м²,12,-1,7.916194e+10,19500000,3,74.7,-1.0,1999

Вместо районов будем использовать округа

In [33]:
import json
with open("county_district.json", 'r', encoding='utf-8') as file:
    districts = json.load(file)
new_districts = dict()
for i in districts:
    name = i['name']
    county_id = i['county_id']
    new_districts[name] = county_id
with open("county.json", 'r', encoding='utf-8') as file:
    countis = json.load(file)
new_countis = dict()
for i in countis:
    short_name = i['short']
    id_c = i['id']
    new_countis[id_c] = short_name
print(new_countis)
print(new_districts)

df['district'] = df['district'].replace(new_districts)
df.head()

{1: 'СЗАО', 2: 'САО', 3: 'СВАО', 4: 'ЗАО', 5: 'ЦАО', 6: 'ВАО', 7: 'ЮЗАО', 8: 'ЮАО', 9: 'ЮВАО', 10: 'ЗелАО', 11: 'НАО', 12: 'ТАО'}
{'Куркино': 1, 'Митино': 1, 'Покровское-Стрешнево': 1, 'Северное Тушино': 1, 'Строгино': 1, 'Хорошево-Мневники': 1, 'Щукино': 1, 'Южное Тушино': 1, 'Северный (САО)': 2, 'Аэропорт': 2, 'Беговой': 2, 'Бескудниковский': 2, 'Войковский': 2, 'Восточное Дегунино': 2, 'Западное Дегунино': 2, 'Головинский': 2, 'Дмитровский': 2, 'Коптево': 2, 'Левобережный': 2, 'Молжаниновский': 2, 'Савеловский': 2, 'Сокол': 2, 'Тимирязевский': 2, 'Ховрино': 2, 'Хорошевский': 2, 'Алексеевский': 3, 'Алтуфьевский': 3, 'Бабушкинский': 3, 'Бибирево': 3, 'Бутырский': 3, 'Лианозово': 3, 'Лосиноостровский': 3, 'Марфино': 3, 'Марьина Роща': 3, 'Останкинский': 3, 'Отрадное': 3, 'Ростокино': 3, 'Свиблово': 3, 'Северное Медведково': 3, 'Южное Медведково': 3, 'Северный': 3, 'Ярославский': 3, 'Внуково': 4, 'Дорогомилово': 4, 'Крылатское': 4, 'Кунцево': 4, 'Можайский': 4, 'Ново-Переделкино': 4, 'Очаково-Матвеевское': 4, 'Проспект Вернадского': 4, 'Раменки': 4, 'Солнцево': 4, 'Тропарево-Никулино': 4, 'Филевский Парк': 4, 'Фили-Давыдково': 4, 'Арбат': 5, 'Басманный': 5, 'Замоскворечье': 5, 'Красносельский': 5, 'Мещанский': 5, 'Пресненский': 5, 'Таганский': 5, 'Тверской': 5, 'Хамовники': 5, 'Якиманка': 5, 'Богородское': 6, 'Вешняки': 6, 'Восточное Измайлово': 6, 'Северное Измайлово': 6, 'Восточный': 6, 'Гольяново': 6, 'Ивановское': 6, 'Измайлово': 6, 'Косино-Ухтомский': 6, 'Метрогородок': 6, 'Новогиреево': 6, 'Новокосино': 6, 'Перово': 6, 'Преображенское': 6, 'Соколиная Гора': 6, 'Сокольники': 6, 'Академический': 7, 'Гагаринский': 7, 'Зюзино': 7, 'Коньково': 7, 'Котловка': 7, 'Ломоносовский': 7, 'Обручевский': 7, 'Северное Бутово': 7, 'Южное Бутово': 7, 'Теплый Стан': 7, 'Черемушки': 7, 'Ясенево': 7, 'Бирюлево Восточное': 8, 'Бирюлево Западное': 8, 'Братеево': 8, 'Даниловский': 8, 'Донской': 8, 'Зябликово': 8, 'Москворечье-Сабурово': 8, 'Нагатино-Садовники': 8, 'Нагатинский Затон': 8, 'Нагорный': 8, 'Орехово-Борисово Северное': 8, 'Орехово-Борисово Южное': 8, 'Царицыно': 8, 'Чертаново Северное': 8, 'Чертаново Центральное': 8, 'Чертаново Южное': 8, 'Выхино-Жулебино': 9, 'Капотня': 9, 'Кузьминки': 9, 'Лефортово': 9, 'Люблино': 9, 'Марьино': 9, 'Некрасовка': 9, 'Нижегородский': 9, 'Печатники': 9, 'Рязанский': 9, 'Текстильщики': 9, 'Южнопортовый': 9, 'Крюково': 10, 'Матушкино': 10, 'Савёлки': 10, 'Силино': 10, 'Старое Крюково': 10, 'Внуковское': 11, 'Воскресенское': 11, 'Десёновское': 11, 'Кокошкино': 11, 'Марушкинское': 11, 'Московский': 11, 'Мосрентген': 11, 'Рязановское': 11, 'Сосенское': 11, 'Филимонковское': 11, 'Щербинка': 11, 'Вороновское': 12, 'Киевский': 12, 'Кленовское': 12, 'Краснопахорское': 12, 'Михайлово-Ярцевское': 12, 'Новофедоровское': 12, 'Первомайское': 12, 'Роговское': 12, 'Троицк': 12, 'Щаповское': 12}

,district,finish_type,floor,floors_count,heating_type,house_material_type,kitchen_meters,living_meters,metro_distance,object_type,phone,price,rooms_count,total_meters,transport_score,year_of_construction
0,4,Без отделки,35,56,-1,Монолитный,6 м²,"33,3 м²",19,-1,7.923071e+10,28127104,2,51.3,5.2,2024
1,4,-1,9,19,-1,-1,18 м²,20 м²,16,-1,7.915314e+10,41500000,2,67.0,-1.0,2004
2,Филевский парк,-1,7,8,-1,-1,15 м²,20 м²,11,-1,7.916816e+10,17850000,2,40.0,-1.0,1960
3,4,Без отделки,33,56,-1,Монолитный,"6,1 м²","44,8 м²",19,-1,7.923071e+10,38320818,2,73.4,5.2,2024
4,4,Чистовая,23,40,-1,-1,-1,49 м²,15,-1,7.985722e+10,51000000,2,54.0,-1.0,2027

Проверим корректность замены

In [34]:
df['district'].value_counts()

district
5                                                                                                                                                             10285
4                                                                                                                                                              5847
2                                                                                                                                                              4814
8                                                                                                                                                              4040
9                                                                                                                                                              2912
                                                                                                                                                              ...
в ЖК Riga Hills площадью 101.19кв.м.\nОтделка черновая. \n\nПолучение ключей от застройщика до июня 2026 года. \n\nRiga Hills - яркий проект бизнес-класса        1
д. Сколково                                                                                                                                                       1
Лучшая 3кв-ра в Алексеевском е3-комн. квартира                                                                                                                    1
Лопатино пгт                                                                                                                                                      1
с. Кленово                                                                                                                                                        1
Name: count, Length: 222, dtype: int64

Исправим недостатки

In [35]:
countis = {
    "Марьина роща": 3,
    "Филевсий парк": 4,
    "Соколиная гора": 6,
    "Нагатинский затон":8,
    "Филевский парк": 4

}
df['district'] = df['district'].replace(countis)
df['district'].value_counts()

district
5                                                                                                                                                             10285
4                                                                                                                                                              6045
2                                                                                                                                                              4814
8                                                                                                                                                              4442
3                                                                                                                                                              3043
                                                                                                                                                              ...
в ЖК Riga Hills площадью 101.19кв.м.\nОтделка черновая. \n\nПолучение ключей от застройщика до июня 2026 года. \n\nRiga Hills - яркий проект бизнес-класса        1
д. Сколково                                                                                                                                                       1
Лучшая 3кв-ра в Алексеевском е3-комн. квартира                                                                                                                    1
Лопатино пгт                                                                                                                                                      1
с. Кленово                                                                                                                                                        1
Name: count, Length: 218, dtype: int64

Удалим мусор

In [36]:
df['district'] = pd.to_numeric(df['district'], errors='coerce')
df = df.dropna(subset=['district'])
df['district'].value_counts()

district
5.0     10285
4.0      6045
2.0      4814
8.0      4442
3.0      3043
9.0      2912
6.0      2759
1.0      2319
7.0      2291
10.0      156
12.0        1
Name: count, dtype: int64

Применим OneHotEncoder для столбца district

In [37]:
df = pd.get_dummies(df, columns=['district'])
df.head()

,finish_type,floor,floors_count,heating_type,house_material_type,kitchen_meters,living_meters,metro_distance,object_type,phone,...,district_2.0,district_3.0,district_4.0,district_5.0,district_6.0,district_7.0,district_8.0,district_9.0,district_10.0,district_12.0
0,Без отделки,35,56,-1,Монолитный,6 м²,"33,3 м²",19,-1,7.923071e+10,...,False,False,True,False,False,False,False,False,False,False
1,-1,9,19,-1,-1,18 м²,20 м²,16,-1,7.915314e+10,...,False,False,True,False,False,False,False,False,False,False
2,-1,7,8,-1,-1,15 м²,20 м²,11,-1,7.916816e+10,...,False,False,True,False,False,False,False,False,False,False
3,Без отделки,33,56,-1,Монолитный,"6,1 м²","44,8 м²",19,-1,7.923071e+10,...,False,False,True,False,False,False,False,False,False,False
4,Чистовая,23,40,-1,-1,-1,49 м²,15,-1,7.985722e+10,...,False,False,True,False,False,False,False,False,False,False

In [38]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

y = df['price']
df.drop(columns=['price'], inplace=True)
X = df
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)



regressor = LinearRegression()
regressor.fit(X_train, y_train)




mine = [10, 18, 3, 60, False, False, False, False, False, False, True, False, False, False]


# or
mine = [mine]

a = regressor.predict(mine)
print(a)

y_pred = regressor.predict(X_test)


score_r2 = r2_score(y_test, y_pred)
mse_score = mean_squared_error(y_test, y_pred)

print(f"score_r2 = {score_r2}")
print(f"mse score = {mse_score}")
from sklearn.metrics import mean_absolute_percentage_error
mape = mean_absolute_percentage_error(y_test, y_pred) * 100
print(f"MAPE: {mape:.1f}%")

ValueError: could not convert string to float: 'Без отделки, предчистовая'

knn

In [15]:
from sklearn.neighbors import KNeighborsRegressor

regressor = KNeighborsRegressor()
regressor.fit(X_train, y_train)


mine = [10, 18, 3, 60, False, False, False, False, False, False, True, False, False, False]


# or
mine = [mine]

a = regressor.predict(mine)
print(a)


y_pred = regressor.predict(X_test)


score_r2 = r2_score(y_test, y_pred)
mse_score = mean_squared_error(y_test, y_pred)

print(f"score_r2 = {score_r2}")
print(f"mse score = {mse_score}")
from sklearn.metrics import mean_absolute_percentage_error
mape = mean_absolute_percentage_error(y_test, y_pred) * 100
print(f"MAPE: {mape:.1f}%")

C:\Users\User\Desktop\Учеба\Project\LinearRegression\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(

[27900000.]
score_r2 = 0.9427211521530968
mse score = 2174125233441645.5
MAPE: 2.8%

tree

In [20]:
from sklearn.tree import DecisionTreeRegressor

from sklearn.metrics import mean_absolute_percentage_error




regressor = DecisionTreeRegressor(max_depth=5)
regressor.fit(X_train, y_train)


mine = [10, 18, 3, 60, False, False, False, False, False, False, True, False, False, False]


# or
mine = [mine]

a = regressor.predict(mine)
print(a)




y_pred = regressor.predict(X_test)


score_r2 = r2_score(y_test, y_pred)
mse_score = mean_squared_error(y_test, y_pred)

print(f"score_r2 = {score_r2}")
print(f"mse score = {mse_score}")
mape = mean_absolute_percentage_error(y_test, y_pred) * 100
print(f"MAPE: {mape:.1f}%")

[19042025.8637733]
score_r2 = 0.745016162519027
mse score = 9678385931729920.0
MAPE: 39.9%

C:\Users\User\Desktop\Учеба\Project\LinearRegression\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(